
public enum RepoTestError: Error, Hashable {
    case cloneFailed
    case missingManifest
    case resolveFailed
    case buildFailed
    case missingLinuxMain
    case testBuildFailed
    case testFailed

    public enum Severity {
        case error
        case info
    }

    public var description: String {
        switch self {
        case .cloneFailed:
            return  "`git clone` failed."
        case .missingManifest:
            return  "`swift package describe` failed. Is it a SwiftPM project?"
        case .resolveFailed:
            return "`swift package resolve` failed."
        case .buildFailed:
            return "`swift build` failed."
        case .missingLinuxMain:
            return "`Tests/LinuxMain.swift` does not exist. It can be generated by `swift test --generate-linuxmain` or using Sourcery."
        case .testBuildFailed:
            return "`swift build --build-tests` failed."
        case .testFailed:
            return "`swift test` failed."
        }
    }

    public var severity: Severity {
        switch self {
        case .missingManifest, .missingLinuxMain:
            return .info
        default:
            return .error
        }
    }
}